### ISSUE TITLE
Mod directory name

### ISSUE THREAD

**Issue by Scherub** [captainfoam/SPT-KeepYourEquipment#7]
I've replaced your previous mod (v1.0.3) version with the latest one (v1.2.0). Both archives are extracted into directories with different names:

- KeepYourEquipment-1.0.3
- KeepYourEquipment-1.2.0

Your installation instruction says: 'Download the archive from the [releases page](https://github.com/captainfoam/SPT-KeepYourEquipment/releases) and extract into the user/mods folder.'

The launcher now displays a warning symbol next to the old and deleted one, and additionally the new one.

![image](https://github.com/captainfoam/SPT-KeepYourEquipment/assets/24685229/c8b48e44-a507-47ac-b810-f80127c0cd81)

Looking at the three other mods I have installed, I would presume, that using the same mod folder name would probably not lead to this problem. But that's just a guess.

**Comment by captainfoam** [comment]
That's fair, I kept the names different thinking users would remember to delete the old ones. It seems to be more standard practice with these mods to keep the same name so I'll do that 😄 

Release 1.3.0 now does this: https://github.com/captainfoam/SPT-KeepYourEquipment/releases/tag/1.3.0

**Comment by Scherub** [comment]
> That's fair, I kept the names different thinking users would remember to delete the old ones
The thing is, that deleting the old mod doesn't remove it from the 'profile-id'.json. SPT seems to treat it as two different mods, so I had to manually remove it from the json file. But now that you've changed it, everything should be fine. Thank you for your work! :)
